---
- name: install nginx
  yum:
    name: nginx
    state: installed

- name: open http port
  firewalld:
    service: http
    immediate: yes
    permanent: yes
    state: enabled

- name: enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Replace nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - nginx reload

- name: Create home directory for virtual domains
  file:
    path: /var/www/{{ item }}
    state: directory
  with_items: "{{ nginx_vhosts }}"

- name: Add virtual domains
  template:
    src: templates/nginx_vhost.conf.j2
    dest: /etc/nginx/conf.d/{{ item }}.conf
  with_items: "{{ nginx_vhosts }}"
  notify:
    - nginx reload
